export const ROUTE_PATH = {
  default: "/",
  contact: "/contact",
  about: "/about",
  cart: "/cart",
  shipping: "/shipping",
  confirmOrder: "/confirm-order",
  paymentSuccess: "/payment-success",
  login: "/login",
  profile: "/profile",
  myOrders: "/my-orders",
  orderDetails: "/order-details",
  adminDashboard: "/admin/dashboard",
  adminUsers: "/admin/users",
  adminOrders: "/admin/orders",
  notFount: "*",
};
